application: snider-cashregister
version: default
runtime: python
api_version: 1

handlers:
  - url: /favicon.ico
    static_files: misc/favicon.ico
    upload: favicon.ico
  - url: /beardcap.jpg
    static_files: misc/beardcap.jpg
    upload: misc/beardcap.jpg
  - url: /org_admin(/.*)?
    script: org_admin.py
    login: admin
  - url: /.*
    script: home.py

error_handlers:
  - file: misc/default_error.html
  - error_code: over_quota
    file: misc/over_quota.html
  - error_code: timeout
    file: misc/timeout.html

builtins:
  - datastore_admin: on
  - remote_api: on
  - deferred: on

admin_console:
  pages:
  - name: Organization Admin
    url: /org_admin

skip_files:
- ^(.*/)?app\.yaml
- ^(.*/)?app\.yml
- ^(.*/)?index\.yaml
- ^(.*/)?index\.yml
- ^(.*/)?#.*#
- ^(.*/)?.*~
- ^(.*/)?.*\.py[co]
- ^(.*/)?.*/RCS/.*
- ^(.*/)?\..*
- ^(.*/)?.*\.bak$
- ^lib/paste.*$