#!/bin/bash
# A small shell script to start the dev server

if [ -z "$1" ]
then
  exit;
fi

source scripts/BUILD "$1";

dev_appserver.py --skip_sdk_update_check --allow_skipped_files --port=8080 --address=0.0.0.0 "build_out/$1"
